### ISSUE TITLE
Default cert is expired

### ISSUE THREAD

**Issue by routelastresort** [Juniper/contrail-go-api#1]
`./cli -os-auth-url=https://contrailhost:8143 -os-password=blah -os-username=blah -server=192.168.3.1 -port=8082 network-show
Post https://192.168.3.1:8143/tokens: x509: certificate has expired or is not yet valid`

I'll make another Contrail lab before messing with the certs.  This tool has a lot of potential (cross-compiling for other target platforms, etc.).  I haven't gone through the code, but are there any shortcuts for ignoring certs?

**Comment by pedro-r-marques** [comment]
I've tested with os-auth-url=http://contrailhost:5000 (i.e. keystone without SSL). Didn't test with SSL.

**Comment by routelastresort** [comment]
Works - many thanks!  Now, to see if I can cross-compile it on Linux, for OS X! :+1:
